Repository athackst/mkdocs-simple-plugin, pull requests merged in 2021-03, with the labels that each got.

#121 Refactor semilterate to a class
  .gitignore
  .vscode/tasks.json
  mkdocs_simple_plugin/plugin.py
Labels: test-deploy

#132 update setup.py at each release draft
  .github/workflows/release.yml
  .github/workflows/release_draft.yml
Labels: maintanence

#133 Maint/fix typo
  .github/pr-labeler.yml
  .github/workflows/release_draft.yml
Labels: maintenance

#134 cleanup workflows and update release-drafter template
  .github/bump_tag.sh
  .github/cleanup_tag.sh
  .github/release-drafter.yml
  docker/build_local.sh
Labels: maintenance

#135 Update release workflow to use VERSION file
  .github/workflows/release.yml
  .github/workflows/release_draft.yml
  Dockerfile
  VERSION
  setup.py
Labels: maintenance

#138 fix: Make extraction w/ no start pattern active from beginning
  examples/.pages
  examples/ok-mkdocs-custom-extract/README.md
  examples/ok-mkdocs-custom-extract/fibo.grepout
  examples/ok-mkdocs-custom-extract/fibo.litcoffee
  examples/ok-mkdocs-custom-extract/mkdocs-test.yml
  mkdocs_simple_plugin/plugin.py
  mkdocs_simple_plugin/semiliterate.py
  tests/test.bats
Labels: bug

#140 update readme
  .github/pr-labeler.yml
  mkdocs.yml
  mkdocs_simple_plugin/README.md
Labels: docs

#141 return replace to original implementation by fixing drop lines
  README.md
  examples/.pages
  examples/ok-mkdocs-custom-extract/README.md
  examples/ok-source-replace/README.md
  examples/ok-source-replace/mkdocs-test.yml
  examples/ok-source-replace/module.grepout
  examples/ok-source-replace/module.py
  examples/ok-source-with-snippet/module.py
  examples/ok-source-with-snippet/snippet2.grepout
  mkdocs.yml
  mkdocs_simple_plugin/README.md
  mkdocs_simple_plugin/generator.py
  mkdocs_simple_plugin/plugin.py
  mkdocs_simple_plugin/semiliterate.py
  tests/test.bats
  tests/test_lint.sh
Labels: bug

#142 fixed vscode clean task
  .vscode/tasks.json
Labels: maintenance

#143 Update grep results to grab all lines
  examples/ok-mkdocs-custom-extract/fibo.grepout
  examples/ok-source-extract/main.grepout
  examples/ok-source-extract/module.grepout
  examples/ok-source-replace/module.grepout
  examples/ok-source-with-snippet/module.grepout
  examples/ok-source-with-snippet/snippet.grepout
  examples/ok-source-with-snippet/snippet2.grepout
  examples/ok-with-macros/module.grepout
  examples/ok-with-mkdocstrings/module.grepout
  mkdocs_simple_plugin/plugin.py
  tests/test.bats
Labels: maintenance

#144 use full path glob matching for ignore folders
  mkdocs_simple_plugin/plugin.py
Labels: feature

#145 Add example readme generator.
  .vscode/launch.json
  .vscode/tasks.json
  examples/.pages
  examples/README.md.jinja
  examples/gen_readme.py
  examples/ok-mkdocs-custom-extract/README.md
  examples/ok-mkdocs-custom-extract/mkdocs-test.yml
  examples/ok-mkdocs-docs-extensions/README.md
  examples/ok-mkdocs-docs-extensions/mkdocs-test.yml
  examples/ok-mkdocs-docs-ignore/README.md
  examples/ok-mkdocs-docs-ignore/mkdocs-test.yml
  examples/ok-mkdocs-docs-ignore/other-folder/subfolder/draft.md
  examples/ok-mkdocs-docs-ignore/other-folder/subfolder/index.md
  examples/ok-mkdocs-docs-include/README.md
  examples/ok-mkdocs-docs-include/mkdocs-test.yml
  examples/ok-mkdocs-docs-merge/README.md
  examples/ok-mkdocs-docs-merge/mkdocs-test.yml
  examples/ok-mkdocs-docs-no-merge/README.md
  examples/ok-mkdocs-docs-no-merge/mkdocs-test.yml
  examples/ok-mkdocs-ignore-site-dir/mkdocs-test.yml
  examples/ok-mkdocs-readme/README.md
  examples/ok-mkdocs-readme/mkdocs-test.yml
  examples/ok-source-extract/README.md
  examples/ok-source-extract/mkdocs-test.yml
  examples/ok-source-replace/README.md
  examples/ok-source-replace/mkdocs-test.yml
  examples/ok-source-with-snippet/README.md
  examples/ok-source-with-snippet/mkdocs-test.yml
  examples/ok-with-macros/README.md
  examples/ok-with-macros/example.md
  examples/ok-with-macros/mkdocs-test.yml
  examples/ok-with-macros/module.py
  examples/ok-with-mkdocstrings/README.md
  examples/ok-with-mkdocstrings/mkdocs-test.yml
  examples/ok-with-rename/README.md
  examples/ok-with-rename/mkdocs-test.yml
  mkdocs.yml
Labels: maintenance

#146 use more snippets in docs
  .vscode/tasks.json
  README.md
  mkdocs_simple_plugin/README.md
  mkdocs_simple_plugin/generator.py
  mkdocs_simple_plugin/plugin.py
  setup.py
  tests/test_local.sh
Labels: docs

#148 add build script
  .github/workflows/publish_docs.yml
  .github/workflows/test.yml
  .vscode/tasks.json
  build.sh
  examples/.gitignore
  examples/ok-mkdocs-custom-extract/README.md
  examples/ok-mkdocs-docs-extensions/README.md
  examples/ok-mkdocs-docs-ignore/README.md
  examples/ok-mkdocs-docs-include/README.md
  examples/ok-mkdocs-docs-merge/README.md
  examples/ok-mkdocs-docs-no-merge/README.md
  examples/ok-mkdocs-readme/README.md
  examples/ok-source-extract/README.md
  examples/ok-source-replace/README.md
  examples/ok-source-with-snippet/README.md
  examples/ok-with-macros/README.md
  examples/ok-with-mkdocstrings/README.md
  examples/ok-with-rename/README.md
  test.sh
  tests/test_local.sh
Labels: maintenance

#150 update publish docs task
  .github/workflows/publish_docs.yml
Labels: maintenance, test-docs

#151 fix docker release workflow
  .github/workflows/release.yml
  docker/build_local.sh
Labels: maintenance

#152 correct site names in examples to use folder name
  examples/ok-mkdocs-config/mkdocs-test.yml
  examples/ok-mkdocs-custom-extract/mkdocs-test.yml
  examples/ok-mkdocs-docs-extensions/mkdocs-test.yml
  examples/ok-mkdocs-docs-ignore/mkdocs-test.yml
  examples/ok-mkdocs-docs-include/mkdocs-test.yml
  examples/ok-mkdocs-docs-merge/mkdocs-test.yml
  examples/ok-mkdocs-docs-no-merge/mkdocs-test.yml
  examples/ok-mkdocs-ignore-site-dir/mkdocs-test.yml
  examples/ok-mkdocs-readme/mkdocs-test.yml
  examples/ok-source-extract/mkdocs-test.yml
  examples/ok-source-replace/mkdocs-test.yml
  examples/ok-source-with-snippet/mkdocs-test.yml
  examples/ok-with-macros/mkdocs-test.yml
  examples/ok-with-macros/module.grepout
  examples/ok-with-mkdocstrings/mkdocs-test.yml
  examples/ok-with-rename/mkdocs-test.yml
  tests/test.bats
Labels: docs

#153 Capture all lines in scripts after start pattern until stop.
  .devcontainer/devcontainer.json
  .github/workflows/test.yml
  .vscode/tasks.json
  README.md
  build.sh
  mkdocs_simple_plugin/README.md
  mkdocs_simple_plugin/plugin.py
  requirements.txt
  test.sh
  tests/test.bats
  tests/test.sh
  tests/test_lint.sh
  tests/test_local.sh
Labels: feature
